### ISSUE TITLE
Add "Wrath of the Cosmos" cards

### ISSUE THREAD

**Issue by dlew** [dlew/android-sotm#14]
Whenever it comes out.

**Comment by mathstuf** [comment]
FWIW, my order just got in. Same with the new promos (Guise, Wager Master, and Omnitron IV).

**Comment by dlew** [comment]
The current issue for me is that the website hasn't been updated, so I
can't get high quality card art. It is otherwise ready to go.

**Comment by mathstuf** [comment]
Sounds good. Thanks!

**Comment by dlew** [comment]
Added as of 8f2b3705d544803fe90d77a8b4e392e82fafc010
